# Generated by Django 4.0.5 on 2022-06-17 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterField(
            model_name='followers',
            name='users_followers',
            field=models.ManyToManyField(blank=True, related_name='users_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='following',
            name='users_following',
            field=models.ManyToManyField(blank=True, related_name='users_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
