# Generated by Django 4.0.5 on 2022-07-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_account_bio'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='users_accou_usernam_038943_idx'),
        ),
    ]
