# Generated by Django 4.0.5 on 2022-06-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
