# Generated by Django 4.0.5 on 2022-07-08 11:59

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(null=True, upload_to=post.models.get_post_image_path),
        ),
    ]
