# Generated by Django 4.0.5 on 2022-08-03 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_runningtasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunningTasks',
            new_name='PostCreateTask',
        ),
    ]
