# Generated by Django 4.0.5 on 2022-07-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_last_unread_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='last_unread_message',
            new_name='first_unread_message',
        ),
    ]
