# Generated by Django 4.0.5 on 2022-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatroom_first_unread_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
